### ISSUE TITLE
router_adapter.py

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp_cors#19]
I believe it worth to be renamed into abc.py -- nice to have all ABC in the same place, `router_adapter.py` is not good name for all possible abcs.

`RouterAdapter` should be renamed into `AbstractRouterAdapter` or something like this.

We can do renaming without making a harm: the library is very young and most likely users don't use `RouterAdapter` and `router_adapter.py` explicitly.

Let's make renaming right now, later it will be more painful.

**Comment by rutsky** [comment]
I agree, please take a look at #20 that addresses this issue.
