### ISSUE TITLE
Use of type annotations

### ISSUE THREAD

**Issue by rutsky** [aio-libs/aiohttp_cors#2]
@asvetlov:

> Say, I doubt using types in annotations make sense.
> They are neither checked in runtime as I see nor pep 484 compatible.

@asvetlov, can you explain why they are not PEP 484 compatible?

E.g. [this](https://github.com/aio-libs/aiohttp_cors/blob/master/src/aiohttp_cors/__init__.py#L362) looks like a proper type annotation:

```
from aiohttp import web
...
class CorsConfig:
...
def setup(app: web.Application, *, defaults: dict=None) -> CorsConfig:
```

There should be `collections.abc.Mapping` instead of `dict` but other parts looks correct to me.

Type annotations *yet* not used at runtime, but can be used right now for documentation purposes and as hints for IDEs like PyCharm (PyCharm right now has limited support of them).

**Comment by asvetlov** [comment]
I believe we should use https://www.python.org/dev/peps/pep-0484/#generics for container types.

I never used pep 484 compatible code before but like to experiment.

Well, let's leave type annotations but use generics for containers.
https://pypi.python.org/pypi/typing is a backport for Python 3.4
