### ISSUE TITLE
Consider making methods coroutine

### ISSUE THREAD

**Issue by rutsky** [aio-libs/aiohttp_cors#21]
Currently all public API can be expressed in the following example:

```python
class RouterAdapter(AbstractRouterAdapter):
    def route_methods(self, route):
        """Returns list of HTTP methods that route handles"""

    def add_options_method_handler(self, route, handler):
        """Add OPTIONS method request handler that will be issued at the same
        paths as provided `route`.

        :return: Newly added route.
        """

router_adapter = RouterAdapter()
cors = aiohttp_cors.setup(app, router_adapter=router_adapter, ...)
cors.add(route, ...)
```

Is any of these methods may be required to be coroutines?

E.g. is it reasonable to assume that `router.add_route()` will never be coroutine for custom routers?

**Comment by asvetlov** [comment]
Yes, `router.add_route` is non-coroutine but it is not part of `AbstractRouter` ABC.
Custom router may change `add_route` to coroutine or even don't have the method.
That means `aiohttp_cors` is just not compatible with these custom routers.

Thus I suggest leaving methods from `RouterAdapter` as-is.

**Comment by rutsky** [comment]
Ok, I leave methods as-is. Thanks for the response.
