### ISSUE TITLE
OOP view

### ISSUE THREAD

**Issue by WolkoDav** [aio-libs/aiohttp_cors#28]
Can I create views in OOP style? How in tornado or in Django CBV.

**Comment by asvetlov** [comment]
Sorry, I don't follow.
router registers any callable accepting the single `request` argument.
What forbid you to use class inheritance etc for organizing handlers in desirable way?

 BTW The question should be asked in *aiohttp* itself not CORS.

**Comment by WolkoDav** [comment]
I create new route as: (method, url, handler). If I create class:
```
class Handler():
    def get(self, request):
        ...
    def post(self, request):
        ...
```
I will have to add twice the class into routing for get and post method.

**Comment by asvetlov** [comment]
I still don't understand what is your question? 
What do you want to achieve?

**Comment by WolkoDav** [comment]
I want create class handler as shown below and it into router for application:
```
app.router.add_route(url, handler)
```
without method.

**Comment by rutsky** [comment]
@WolkoDav, I don't really understand your question/bug report.
I think what you are asking is outside `aiohttp_cors` library scope, as @asvetlov mentioned.
(`aiohttp_cors` is a small library that adds Cross Origin Resource Sharing support to `aiohttp`.)

I suggest you to ask this question on [aio-libs](https://groups.google.com/forum/#!forum/aio-libs) mailing list (also you can write there in Russian language).

If you want to use something similar to Class Based View you can implement it by yourself, e.g. as @asvetlov pointed [here](http://stackoverflow.com/a/32825823/391865).
There is no standard CBV wrappers implementations for aiohttp AFAIK, but it's not hard to write one for yourself (and even contribute it to aiohttp if you manage to implement good generic and useful CBV).

**Comment by rutsky** [comment]
Note about CBV: I see that @sloria implemented one in [aiohttp_utils](https://github.com/sloria/aiohttp_utils) library: https://aiohttp-utils.readthedocs.org/en/latest/index.html

`aiohttp_cors` shouldn't work with `aiohttp_utils`, but I think support can be implemented pretty easily.
