### ISSUE TITLE
Support new Resources in aiohttp >= 0.21.0

### ISSUE THREAD

**Issue by rutsky** [aio-libs/aiohttp_cors#30]
Currently aiohttp_cors tests fails with master version of aiohttp: https://travis-ci.org/rutsky/aiohttp_cors/jobs/105379563

**Comment by rutsky** [comment]
@asvetlov when aiohttp 0.21.0 planned to be released?

I need some time to fix aiohttp_cors to fix it to work with new Resources.

**Comment by asvetlov** [comment]
I'll publish new version next week probably.

**Comment by mattupstate** [comment]
Any progress here?

**Comment by rutsky** [comment]
@mattupstate I started support of new Resources today, I hope to finish and release new version of aiohttp_cors during few days.

**Comment by rutsky** [comment]
PR #35 fixes this issue. I'll make new release soon.

**Comment by rutsky** [comment]
@mattupstate I released [aiohttp_cors 0.4.0](https://pypi.python.org/pypi/aiohttp_cors/0.4.0) with new Resources support, please try it.
