### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by rutsky** [aio-libs/aiohttp_cors#5]
I want to use [semantic versioning](http://semver.org/) for versioning aiohttp_cors.

E.g. release not yet stable version as 0.1.0, 0.2.0, ..., and subsequent stable versions as 1.0.0, 2.0.0, ..., according to semantic versioning rules.

Any objections?

/cc @asvetlov

**Comment by asvetlov** [comment]
Feel free to publish aiohttp_cors 1.0.0 but I think aiohttp is not ready yet for 1.0.
I prefer 0.1.x for now.

**Comment by rutsky** [comment]
Sound reasonable, I'll stay with 0.x.x versions for now.
